version: '2'
services:
  probe:
    container_name: weavescope_probe
    image: dilgerm/rpi-scope
    network_mode: "host"
    pid: "host"
    restart: "always"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
