FROM openthings/zrock_rpi

MAINTAINER openthings <openthings@163.com>

COPY ./bin/ ~/ipfs

#RUN mkdir -p /home/znet &&\
#	cd /home/znet &&\
#	wget git.io/cow -O cow.sh &&\
#	chmod +x cow.sh &&\
#	./cow.sh

#传入配置文件
#COPY cow /root/.cow

EXPOSE 4001 5001 8080

WORKDIR /home/znet
CMD ["/home/znet/cow"]
#CMD ["usr/local/bin/cow"]
