FROM resin/rpi-raspbian

#FROM hypriot/rpi-alpine
#FROM arm32v6/alpine

MAINTAINER openthings <openthings@163.com>

#COPY ./bin /usr/local/bin
#COPY ./bin /tmp/

#RUN apk update && apk upgrade && apk add bash wget curl openssl nano

EXPOSE 9999

WORKDIR /home/znet
CMD ["bash"]

